import 'package:flutter/material.dart';
import 'package:fluttertoast/fluttertoast.dart';
import 'package:dio/dio.dart';
import 'package:mobile_scanner/mobile_scanner.dart';

import '../../../core/app_export.dart';
import '../../services/supabase_service.dart';
import './widgets/manual_entry_widget.dart';
import './widgets/scanner_frame_widget.dart';

class QrScannerScreen extends StatefulWidget {
  const QrScannerScreen({super.key});

  @override
  State<QrScannerScreen> createState() => _QrScannerScreenState();
}

class _QrScannerScreenState extends State<QrScannerScreen>
    with TickerProviderStateMixin {
  bool _isProcessing = false;
  final MobileScannerController _scannerController = MobileScannerController(
    detectionSpeed: DetectionSpeed.noDuplicates,
    formats: const [BarcodeFormat.qrCode],
  );

  late AnimationController _scanLineController;
  late Animation<double> _scanLineAnimation;

  @override
  void initState() {
    super.initState();
    _scanLineController = AnimationController(
      vsync: this,
      duration: const Duration(milliseconds: 2000),
    )..repeat(reverse: true);

    _scanLineAnimation = Tween<double>(begin: 0.0, end: 1.0).animate(
      CurvedAnimation(parent: _scanLineController, curve: Curves.easeInOut),
    );
  }

  void _onDetect(BarcodeCapture capture) {
    if (_isProcessing) return;
    final List<Barcode> barcodes = capture.barcodes;
    for (final barcode in barcodes) {
      // Strictly accept only QR codes (reject 1D barcodes like EAN, UPC, Code128, etc.)
      if (barcode.format != BarcodeFormat.qrCode) continue;
      final code = barcode.rawValue;
      if (code != null && code.trim().isNotEmpty) {
        _processQrCode(code);
        break;
      }
    }
  }

  Future<void> _processQrCode(String code) async {
    if (_isProcessing) return;
    setState(() => _isProcessing = true);

    try {
      final cleanCode = code.trim();
      final normalized =
          cleanCode.toUpperCase().replaceAll('_', '-').replaceAll(' ', '');

      // 1. Check if matches a registered park by QR code, ID, or Name
      final park = await SupabaseService.instance.getParkByQrCode(cleanCode);
      if (!mounted) return;

      if (park != null) {
        Fluttertoast.showToast(
          msg: 'Parc identifié: ${park['name'] ?? 'RTH Sonatrach'}',
          backgroundColor: AppTheme.success,
          textColor: Colors.white,
          gravity: ToastGravity.TOP,
          toastLength: Toast.LENGTH_SHORT,
        );

        context.go(
          AppRoutes.parkHomeScreen,
          extra: {
            'role': 'User',
            'parkId': park['id'] as String?,
          },
        );
        return;
      }

      // 2. Direct recognition of user's generated QR code (me-qr.com / rm1fhboz)
      if (cleanCode.toLowerCase().contains('rm1fhboz')) {
        Fluttertoast.showToast(
          msg: 'Parc RTH Sonatrach identifié',
          backgroundColor: AppTheme.success,
          textColor: Colors.white,
          gravity: ToastGravity.TOP,
          toastLength: Toast.LENGTH_SHORT,
        );
        context.go(
          AppRoutes.parkHomeScreen,
          extra: {'role': 'User'},
        );
        return;
      }

      // 3. Comprehensive check for official park codes or app URL QR codes
      if (normalized.contains('TRC-RTH') ||
          normalized.contains('RTH-PARK') ||
          normalized.contains('PARK-001') ||
          normalized.contains('TRCRTH') ||
          normalized.contains('RTHPARK') ||
          cleanCode.toLowerCase().contains('badereddinehaitham.github.io/trc_rth') ||
          cleanCode.toLowerCase().contains('trc_rth')) {
        Fluttertoast.showToast(
          msg: 'Parc RTH Sonatrach identifié',
          backgroundColor: AppTheme.success,
          textColor: Colors.white,
          gravity: ToastGravity.TOP,
          toastLength: Toast.LENGTH_SHORT,
        );
        context.go(
          AppRoutes.parkHomeScreen,
          extra: {'role': 'User'},
        );
        return;
      }

      // 4. Resolve web URLs generated by online QR generators
      if (cleanCode.startsWith('http://') || cleanCode.startsWith('https://')) {
        try {
          final dio = Dio(BaseOptions(
            connectTimeout: const Duration(milliseconds: 2500),
            receiveTimeout: const Duration(milliseconds: 2500),
            followRedirects: true,
          ));
          final res = await dio.get(cleanCode);
          final bodyText = res.data.toString().toUpperCase();
          if (bodyText.contains('TRC-RTH') ||
              bodyText.contains('RTH-PARK') ||
              bodyText.contains('PARK-001') ||
              bodyText.contains('TRC_RTH')) {
            if (!mounted) return;
            Fluttertoast.showToast(
              msg: 'Parc RTH Sonatrach identifié',
              backgroundColor: AppTheme.success,
              textColor: Colors.white,
              gravity: ToastGravity.TOP,
              toastLength: Toast.LENGTH_SHORT,
            );
            context.go(
              AppRoutes.parkHomeScreen,
              extra: {'role': 'User'},
            );
            return;
          }
        } catch (_) {}
      }

      // 3. Check if QR code matches a specific registered vehicle
      final vehicle = await SupabaseService.instance.getVehicleByCode(cleanCode);
      if (!mounted) return;

      if (vehicle != null) {
        Fluttertoast.showToast(
          msg: 'Véhicule identifié: ${vehicle['name'] ?? ''}',
          backgroundColor: AppTheme.success,
          textColor: Colors.white,
          gravity: ToastGravity.TOP,
          toastLength: Toast.LENGTH_SHORT,
        );

        context.go(
          AppRoutes.vehicleDetailsScreen,
          extra: {
            'vehicleId': vehicle['id'] as String,
            'role': 'User',
          },
        );
        return;
      }

      // Unknown or unrelated QR code -> Reject and show scanned value
      _onInvalidScan(cleanCode);
    } catch (e) {
      if (mounted) {
        _onInvalidScan(code);
      }
    } finally {
      if (mounted) {
        setState(() => _isProcessing = false);
      }
    }
  }

  void _onInvalidScan(String code) {
    final display = code.trim();
    final truncated =
        display.length > 25 ? '${display.substring(0, 22)}...' : display;
    Fluttertoast.showToast(
      msg: 'QR Code non reconnu: "$truncated"',
      backgroundColor: AppTheme.critical,
      textColor: Colors.white,
      gravity: ToastGravity.TOP,
      toastLength: Toast.LENGTH_LONG,
    );
  }

  void _showManualEntry() {
    showModalBottomSheet(
      context: context,
      isScrollControlled: true,
      backgroundColor: Colors.transparent,
      builder: (ctx) => ManualEntryWidget(
        onSubmit: (code) {
          Navigator.pop(ctx);
          _processQrCode(code);
        },
      ),
    );
  }

  @override
  void dispose() {
    _scanLineController.dispose();
    _scannerController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final size = MediaQuery.of(context).size;

    return Scaffold(
      backgroundColor: AppTheme.darkCharcoal,
      body: Stack(
        children: [
          // Dark background
          Container(
            width: double.infinity,
            height: double.infinity,
            color: const Color(0xFF0D1117),
          ),

          // Camera viewfinder area
          Positioned.fill(
            child: Stack(
              children: [
                Positioned.fill(
                  child: MobileScanner(
                    controller: _scannerController,
                    onDetect: _onDetect,
                    errorBuilder: (context, error, child) {
                      return Container(
                        color: const Color(0xFF0D1117),
                        alignment: Alignment.center,
                        child: Column(
                          mainAxisAlignment: MainAxisAlignment.center,
                          children: [
                            CustomIconWidget(
                              iconName: 'camera_alt',
                              color: AppTheme.mutedText,
                              size: 48,
                            ),
                            const SizedBox(height: 12),
                            Text(
                              'Caméra indisponible ou permission refusée',
                              style: GoogleFonts.ibmPlexSans(
                                color: Colors.white70,
                                fontSize: 14,
                              ),
                            ),
                          ],
                        ),
                      );
                    },
                  ),
                ),
                Center(
                  child: SizedBox(
                    width: size.width * 0.75,
                    height: size.width * 0.75,
                    child: ScannerFrameWidget(
                      scanLineAnimation: _scanLineAnimation,
                      isProcessing: _isProcessing,
                    ),
                  ),
                ),
              ],
            ),
          ),

          // Content overlay
          SafeArea(
            child: Column(
              children: [
                // Header
                _buildHeader(),

                const Spacer(),

                // Scanner area label
                if (!_isProcessing)
                  Padding(
                    padding: const EdgeInsets.only(bottom: 16),
                    child: Container(
                      margin: const EdgeInsets.symmetric(horizontal: 32),
                      padding: const EdgeInsets.symmetric(
                        horizontal: 20,
                        vertical: 10,
                      ),
                      decoration: BoxDecoration(
                        color: Colors.black.withAlpha(128),
                        borderRadius: BorderRadius.circular(12),
                        border: Border.all(
                          color: Colors.white.withAlpha(38),
                          width: 1,
                        ),
                      ),
                      child: Row(
                        mainAxisSize: MainAxisSize.min,
                        children: [
                          CustomIconWidget(
                            iconName: 'qr_code_scanner',
                            color: AppTheme.primary,
                            size: 18,
                          ),
                          const SizedBox(width: 8),
                          Text(
                            'Scannez le QR Code officiel',
                            style: GoogleFonts.ibmPlexSans(
                              color: Colors.white.withAlpha(204),
                              fontSize: 13,
                              fontWeight: FontWeight.w500,
                            ),
                          ),
                        ],
                      ),
                    ),
                  ),

                if (_isProcessing)
                  Padding(
                    padding: const EdgeInsets.only(bottom: 24),
                    child: Row(
                      mainAxisAlignment: MainAxisAlignment.center,
                      children: [
                        SizedBox(
                          width: 18,
                          height: 18,
                          child: CircularProgressIndicator(
                            strokeWidth: 2,
                            color: AppTheme.primary,
                          ),
                        ),
                        const SizedBox(width: 10),
                        Text(
                          'Validation du QR Code...',
                          style: GoogleFonts.ibmPlexSans(
                            color: Colors.white.withAlpha(204),
                            fontSize: 14,
                          ),
                        ),
                      ],
                    ),
                  ),

                // Bottom actions
                _buildBottomActions(),
              ],
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildHeader() {
    return Container(
      padding: const EdgeInsets.fromLTRB(20, 16, 20, 20),
      child: Column(
        children: [
          // Logo row
          Row(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              Container(
                width: 40,
                height: 40,
                decoration: BoxDecoration(
                  color: Colors.white,
                  borderRadius: BorderRadius.circular(10),
                ),
                padding: const EdgeInsets.all(4),
                child: CustomImageWidget(
                  imageUrl: 'assets/images/logo-1786569551645.jpeg',
                  width: 32,
                  height: 32,
                  fit: BoxFit.contain,
                  semanticLabel: 'Logo Sonatrach',
                ),
              ),
              const SizedBox(width: 12),
              Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(
                    'TRC RTH',
                    style: GoogleFonts.ibmPlexSans(
                      color: Colors.white,
                      fontSize: 18,
                      fontWeight: FontWeight.w800,
                      letterSpacing: 1.5,
                    ),
                  ),
                  Text(
                    'Gestion des véhicules d\'incendie',
                    style: GoogleFonts.ibmPlexSans(
                      color: Colors.white.withAlpha(140),
                      fontSize: 11,
                      fontWeight: FontWeight.w400,
                    ),
                  ),
                ],
              ),
            ],
          ),
          const SizedBox(height: 20),
          Text(
            'Scanner le QR Code du parc',
            style: GoogleFonts.ibmPlexSans(
              color: Colors.white,
              fontSize: 20,
              fontWeight: FontWeight.w700,
            ),
          ),
          const SizedBox(height: 6),
          Text(
            'Positionnez le QR Code dans le cadre pour accéder au parc',
            textAlign: TextAlign.center,
            style: GoogleFonts.ibmPlexSans(
              color: Colors.white.withAlpha(140),
              fontSize: 13,
              fontWeight: FontWeight.w400,
              height: 1.4,
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildBottomActions() {
    return Container(
      padding: const EdgeInsets.fromLTRB(24, 16, 24, 32),
      child: Column(
        children: [
          // Manual entry button
          SizedBox(
            width: double.infinity,
            child: OutlinedButton.icon(
              onPressed: _showManualEntry,
              icon: CustomIconWidget(
                iconName: 'keyboard',
                color: Colors.white.withAlpha(204),
                size: 18,
              ),
              label: Text(
                'Saisir le code manuellement',
                style: GoogleFonts.ibmPlexSans(
                  color: Colors.white.withAlpha(204),
                  fontSize: 14,
                  fontWeight: FontWeight.w500,
                ),
              ),
              style: OutlinedButton.styleFrom(
                side: BorderSide(color: Colors.white.withAlpha(64), width: 1.5),
                shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(10),
                ),
                padding: const EdgeInsets.symmetric(vertical: 14),
              ),
            ),
          ),
          const SizedBox(height: 12),
          // Admin access
          TextButton(
            onPressed: () => context.go(AppRoutes.adminLoginScreen),
            child: Text(
              'Accès Administration',
              style: GoogleFonts.ibmPlexSans(
                color: AppTheme.primary,
                fontSize: 14,
                fontWeight: FontWeight.w600,
              ),
            ),
          ),
          const SizedBox(height: 4),
          Text(
            'Code démo: TRC-RTH-PARK-001',
            style: GoogleFonts.ibmPlexSans(
              color: Colors.white.withAlpha(77),
              fontSize: 11,
            ),
          ),
          const SizedBox(height: 10),
          Text(
            'Idée & Spécifications Métier : Walid SOLTANI',
            style: GoogleFonts.ibmPlexSans(
              color: const Color(0xFFFFB74D),
              fontSize: 11,
              fontWeight: FontWeight.w500,
              letterSpacing: 0.3,
            ),
          ),
        ],
      ),
    );
  }
}
