name: Build iOS IPA

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Install CocoaPods Dependencies
        run: |
          flutter pub get
          cd ios
          pod install
          cd ..

      - name: Build iOS Application
        run: |
          flutter build ios --release --no-codesign

      - name: Package Valid IPA for Diawi & InstallOnAir
        run: |
          cd build/ios/iphoneos
          mkdir -p Payload
          cp -R Runner.app Payload/
          zip -r -y Sanad_iOS.ipa Payload

      - name: Upload iOS IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Sanad_iOS_IPA
          path: build/ios/iphoneos/Sanad_iOS.ipa
